# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 10

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[battery]
format = '[$symbol]($style)'

[[battery.display]]
threshold = 25
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold orange'

[[battery.display]]
threshold = 75
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = 'bold dimmed green'
format='[$ram $ram_pct]($style) '

[shell]
zsh_indicator = ''
bash_indicator = '\$'
powershell_indicator = '_'
fish_indicator = ''
disabled = false

[username]
show_always = true
style_root = 'bold red'
style_user = 'bold cyan'
format = "[$user]($style) in " 

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[swift]
symbol = "ﯣ "
